name = "wxchat"
main = "worker/index.js"
compatibility_date = "2025-06-17"

# 静态资源配置 - 使用正确的格式
[assets]
directory = "./public"
binding = "ASSETS"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "wxchat"
database_id = "db2a9c2e-3758-42d6-a697-f99d1e290664"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "wxchat"

# 环境变量配置（用于鉴权）
[vars]
# 访问密码（生产环境请修改为强密码）
ACCESS_PASSWORD = "3zHb0d44eW^mzLj"
# JWT密钥（生产环境请使用强随机密钥）
JWT_SECRET = "lazily-plunder-overboard-washer-rants-lingo"
# 会话过期时间（小时）
SESSION_EXPIRE_HOURS = "24"
# 最大登录尝试次数
MAX_LOGIN_ATTEMPTS = "5"

